[workspace]

members = [
    "ch01_getting_started",
    "ch02_guessing_game",
    "ch03_syntax_and_semantics",
    "ch99_rust_learning",
]



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



